apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-hmjczndw
  janus-idp.io/tekton: go-hmjczndw
  backstage.io/kubernetes-id: go-hmjczndw
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-hmjczndw
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
